# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen

generate_doxygen_documentation:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/latex_ubuntu:18.04
  stage: deploy
  before_script:
  - apt update
  - apt install -y doxygen graphviz
  script:
  - doxygen Doxyfile
  - rm -rf /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  - mkdir -p /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  - cp -R doc/* /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  artifacts:
    paths:
    - doc/
  only:
  - master

software_catalogue_entry:
  image: d-reg.hb.dfki.de:5000/ubuntu:overview_generator
  stage: deploy
  script:
  - apt update
  - apt install -y wget
  - wget http://bob.dfki.uni-bremen.de/software_overview/generate.sh
  - sh generate.sh $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME $CI_PROJECT_URL
  only:
  - master

