# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen

include:
   - project: 'build_server/gitlab_ci_includes'
     file: 'api_publish.yml'

build_rock_18.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:18.04
  stage: build
  script:
    - /opt/hooks/build_with_gitlab_ci.bash

build_rock_20.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:20.04
  stage: build
  script:
    - /opt/hooks/build_with_gitlab_ci.bash

run_tests:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:18.04
  stage: test
  script:
  - aup --config
  - aup
  - amake
  - ./build/test/controllers/test_pid_controllers
  - ./build/test/controllers/test_pos_pd_controllers
  - ./build/test/controllers/test_pot_field_controllers
  - ./build/test/core/test_core
  - ./build/test/robot_models/kdl/test_robot_model_kdl
  - ./build/test/scenes/test_velocity_scene
  - ./build/test/scenes/test_velocity_scene_quadratic_cost
  - ./build/test/scenes/test_acceleration_scene
  - ./build/test/solvers/hls/test_hls_solver
  - ./build/test/solvers/qpoases/test_qpoases_solver

software_catalogue_entry:
  image: d-reg.hb.dfki.de:5000/ubuntu:overview_generator
  stage: deploy
  script:
  - apt update
  - apt install -y wget
  - wget http://bob.dfki.uni-bremen.de/software_overview/generate.sh
  - sh generate.sh $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME $CI_PROJECT_URL
  only:
  - master

