# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen

include:
   - project: 'build_server/gitlab_ci_includes'
     file: 'api_publish.yml'
   - project: 'sw-backbone/continuous-integration/ric-backbone-buildconf'
     file: 'gitlab-ci-include.yml'

run_tests:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:18.04
  stage: test
  script:
  - aup --config
  - aup
  - sed -i '1s/^/set(ROCK_TEST_ENABLED ON)\n /' CMakeLists.txt 
  - amake
  - ./build/test/robot_models/kdl/test_robot_model_kdl

software_catalogue_entry:
  image: d-reg.hb.dfki.de:5000/ubuntu:overview_generator
  stage: deploy
  script:
  - apt update
  - apt install -y wget
  - wget http://bob.dfki.uni-bremen.de/software_overview/generate.sh
  - sh generate.sh $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME $CI_PROJECT_URL
  only:
  - master

