# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen

include:
  - project: 'build_server/gitlab_ci_includes'
    file: 'api_publish.yml'
  - project: 'build_server/gitlab_ci_includes'
    file: 'software_catalogue.yml'

build_rock_18.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:18.04
  stage: build
  script:
    - /opt/hooks/build_with_gitlab_ci.bash

#build_rock_20.04:
#  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:20.04
#  stage: build
#  script:
#    - /opt/hooks/build_with_gitlab_ci.bash

run_tests:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:18.04
  stage: test
  script:
  - /opt/hooks/build_with_gitlab_ci.bash
  - cd build/test
  - cd controllers && ./test_pid_controllers && cd ..
  - cd controllers && ./test_pos_pd_controllers && cd ..
  - cd controllers && ./test_pot_field_controllers && cd ..
  - cd core && ./test_core && cd ..
  - cd robot_models/kdl && ./test_robot_model_kdl && cd ../..
  - cd scenes && ./test_velocity_scene && cd ..
  - cd scenes && ./test_velocity_scene_quadratic_cost && cd ..
  - cd scenes && ./test_acceleration_scene && cd ..
  - cd solvers/hls && ./test_hls_solver && cd ../..
  - cd solvers/qpoases && ./test_qpoases_solver && cd ../..


