# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: install
      run: sh scripts/install.sh
    - name: LS
      run: ls 
    - name: test
      run: |
        ./home/runner/work/wbc/wbc/wbc/build/test/controllers/test_pid_controllers
        ./home/runner/work/wbc/wbc/wbc/build/test/controllers/test_pos_pd_controllers
        ./home/runner/work/wbc/wbc/wbc/build/test/controllers/test_pot_field_controllers
        ./home/runner/work/wbc/wbc/wbc/build/test/core/test_core
        ./home/runner/work/wbc/wbc/wbc/build/test/robot_models/kdl/test_robot_model_kdl
        ./home/runner/work/wbc/wbc/wbc/build/test/scenes/test_velocity_scene
        ./home/runner/work/wbc/wbc/wbc/build/test/scenes/test_velocity_scene_quadratic_cost
        ./home/runner/work/wbc/wbc/wbc/build/test/scenes/test_acceleration_scene
        ./home/runner/work/wbc/wbc/wbc/build/test/solvers/hls/test_hls_solver
        ./home/runner/work/wbc/wbc/wbc/build/test/solvers/qpoases/test_qpoases_solver
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc

